In [2]:
'''# 查看一下星期几的分布'''
import numpy as np
import pandas as pd

Mon = np.loadtxt('sum-week/train/Sum-Mon.txt',dtype='int')
Tues = np.loadtxt('sum-week/train/Sum-Tues.txt',dtype='int')
Wed = np.loadtxt('sum-week/train/Sum-Wed.txt',dtype='int')
Thur = np.loadtxt('sum-week/train/Sum-Thur.txt',dtype='int')
Fri = np.loadtxt('sum-week/train/Sum-Fri.txt',dtype='int')
Sat = np.loadtxt('sum-week/train/Sum-Sat.txt',dtype='int')
Sun = np.loadtxt('sum-week/train/Sum-Sun.txt',dtype='int')

In [2]:
data = [Mon, Tues, Wed, Thur, Fri, Sat, Sun]
for index in data:
    print(index.shape)

(160,)
(163,)
(165,)
(166,)
(164,)
(160,)
(54,)


In [20]:
'''我打算把数据切齐一点，就是参照上面的结果，周一到周五各取 160个数据'''
train = np.loadtxt('data_date-weekday-sum.txt',dtype='int')


data_1_5 = []
for index in train:
    if index[1] in range(1,6):
        data_1_5.append(index)

data_1_5

[array([ 1,  3, 68]),
 array([ 2,  4, 36]),
 array([   3,    5, 5565]),
 array([   6,    1, 3396]),
 array([   7,    2, 4146]),
 array([   8,    3, 3096]),
 array([   9,    4, 2713]),
 array([  10,    5, 2409]),
 array([  12,    1, 2735]),
 array([  13,    2, 2386]),
 array([  14,    3, 1901]),
 array([  15,    4, 6072]),
 array([  16,    5, 2716]),
 array([  19,    1, 3903]),
 array([  20,    2, 2700]),
 array([  21,    3, 2700]),
 array([  22,    4, 2073]),
 array([  23,    5, 1702]),
 array([  25,    1, 3377]),
 array([  26,    2, 3016]),
 array([  27,    3, 2586]),
 array([  28,    4, 1652]),
 array([  29,    5, 2726]),
 array([  32,    1, 4094]),
 array([  33,    2, 4059]),
 array([  34,    3, 3741]),
 array([  35,    4, 2567]),
 array([ 36,   5, 761]),
 array([37,  4, 19]),
 array([38,  5, 13]),
 array([  41,    1, 2377]),
 array([  42,    2, 1740]),
 array([  43,    3, 2563]),
 array([  44,    4, 1896]),
 array([  45,    5, 1552]),
 array([  47,    1, 1874]),
 array([  48,    2,

In [15]:
train.shape

(1032, 3)